# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yawirra
email: cadel@cadelwatson.com
description: > # this means to ignore newlines until "baseurl:"
  A worldbuilding project by Cadel Watson
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cadelwatson.com" # the base hostname & protocol for your site
github_username:  kdelwat

# Build settings
markdown: kramdown
